version: '3.8'

services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile.api
    image: api_dockerimg:latest
    ports:
      - "8080:8000"
    env_file:
      - api/.env
    networks:
      - app-network

  frontend:
    build:
      context: ./front-end-nextjs
      dockerfile: Dockerfile.frontend
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8080
    image: frontend_dockerimg:latest
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge