name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install dependencies
        run: cd front-end-nextjs && npm ci

      - name: Build Docker Compose stack
        run: docker-compose build

      - name: Start Docker Compose
        run: docker-compose up -d
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Check running containers
        run: docker ps -a

      - name: Run API tests
        run: docker-compose exec -T api pytest

      - name: Run Frontend tests
        run: |
          cd front-end-nextjs
          npm test

      - name: Stop Docker Compose
        run: docker-compose down

      - name: Print success message
        run: echo "Build and tests completed successfully"
